(part "CM322522-180KL"
    (packageRef "INDM3225X240N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "652-CM322522-180KL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/CM322522-180KL?qs=jraqILX6wiSvRdOCrzjQ4g%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "CM322522-180KL")
    (property "Description" "Power Inductors - SMD 18uH 10% Wirewound")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/cm322522.pdf")
    (property "symbolName1" "CM322522-180KL")
)
