(part "FZT600TA"
    (packageRef "SOT230P700X170-4N")
    (interface
        (port "1" (symbPinId 1) (portName "B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "C_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "E") (portType INOUT))
        (port "4" (symbPinId 4) (portName "C_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "522-FZT600TA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/FZT600TA?qs=fpoYs8%2FwAu8bOWo5PH7jWg%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "FZT600TA")
    (property "Description" "Darlington Transistors NPN Darlington 140V NPN DARLINGTON TRANSISTOR IN SOT223")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/FZT600A.pdf")
    (property "symbolName1" "FZT600TA")
)
