(part "RF1-01A-D-00-75-M"
    (packageRef "RF101AD0075M")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "MH1" (symbPinId 3) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 4) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Adam Tech")
    (property "Manufacturer_Part_Number" "RF1-01A-D-00-75-M")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "BNC R/A LOW PROFILE INSUL PCB SK")
    (property "Datasheet_Link" "https://www.mouser.com/datasheet/3/6015/1/rf1_01a_d_00_75_m_data_sheet.pdf")
    (property "symbolName1" "RF1-01A-D-00-75-M")
)
